Blog/Blog/urls.py
# System Imports:
from django.contrib import admin
from django.urls import path

# My Imports:
from django.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogs.urls')),
]

Blog/blogs/urls.py
"""Defines URL patterns for Blog Posts APP."""

# System Imports
from django.urls import path

# My Imports
from . import views


app_name = 'blogs'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),
]

Blog/blogs/models.py
from django.db import models


# Create your models here.
class BlogPost(models.Model):
    """A topic the user is blogging about."""
    title = models.CharField(max_length=50)
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return a string representation of the model."""
        return f"{self.title}"

Blog/blogs/forms.py
from django import forms
from .models import BlogPost

Blog/blogs/views.py
# System Imports
from django.shortcuts import render

# My Imports
from .models import BlogPost


# Create your views here.
def index(request):
    """The home page for Blogs App"""
    return render(request, 'blogs/index.html')

Blog/blogs/templates/blogs/base.html
<p>
  <a href="{% url 'blogs:index' %}">Blog Posts</a>
</p>

{% block content %}
{% endblock content %}


<p style=" position: absolute; bottom: 0; left: 7; width: 100%; text-align: left;">
&copy; Copyright 2006<script>new Date().getFullYear()>2017&&document.write(" - "+new Date().getFullYear());</script>, Ing. Raúl Girón.</p>

Blog/blogs/templates/blogs/index.html
{% extends "blogs/base.html" %}


{% block content %}

  <p>Blog Posts helps you keep track of your blogs, and for anny topic you register.</p>

{% endblock content %}