pizzeria/pizzas/urls.py
"""Defines URL patterns for pizzas APP."""

# System Imports
from django.urls import path

# My Imports
from . import views

app_name = 'pizzas'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # Page that shows all days of the week
    path('pizzas/', views.pizzas, name='pizzas'),
    # Detail page for a single pizza
    path('pizzas/<int:pizza_id>/', views.pizza, name='pizza'),
]

pizzeria/pizzeria/urls.py
# System Imports:
from django.contrib import admin
from django.urls import path

# My Imports:
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pizzas.urls')),
]

pizzeria/pizzas/models.py
from django.db import models

# Create your models here.
class Pizza(models.Model):
    """A topic the pizza name is about."""
    name = models.CharField(max_length=50)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return a string representation of the model."""
        return self.name

class Topping(models.Model):
    """Specific toppings about each pizza."""
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    name = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    # class Meta:
    #     verbose_name_plural = 'toppings'

    def __str__(self):
        """Return a string representation of the model."""
        if len(self.name) > 50:
            return f"{self.name[:50]}..."
        else:
            return f"{self.name}"

pizzeria/pizzas/views.py
# System Imports
from django.shortcuts import render

# My Imports
from .models import Pizza

# Create your views here.
def index(request):
    """The home page for Pizzas."""
    return render(request, 'pizzas/index.html')

def pizzas(request):
    """Show all kind of pizzas registered."""
    pizzas = Pizza.objects.order_by('date_added')
    context = {'pizzas': pizzas}
    return render(request, 'pizzas/pizzas.html', context)

def pizza(request, pizza_id):
    """Show a single pizza and all its toppings."""
    pizza = Pizza.objects.get(id=pizza_id)
    toppings = pizza.topping_set.order_by('date_added')
    context = {'pizza': pizza, 'toppings': toppings}
    return render(request, 'pizzas/pizza.html', context)

pizzeria/pizzas/templates/pizzas/base.html
<p>
  <a href="{% url 'pizzas:index' %}">Pizzeria</a> -
  <a href="{% url 'pizzas:pizzas' %}">Pizzas</a>
</p>

{% block content %}{% endblock content %}


<p style=" position: absolute; bottom: 0; left: 7; width: 100%; text-align: left;">
&copy; Copyright 2006<script>new Date().getFullYear()>2017&&document.write(" - "+new Date().getFullYear());</script>, Ing. Raúl Girón.</p>

pizzeria/pizzas/templates/pizzas/index.html
{% extends "pizzas/base.html" %}


{% block content %}

  <p>Pizzeria helps you keep track of your pizzas, and for anny topping you register.</p>

{% endblock content %}

pizzeria/pizzas/templates/pizzas/pizza.html
{% extends "pizzas/base.html" %}


{% block content %}

<p>
  Pizza: {{ pizza }}</p>

<p>Toppings</p>
<ul>
  {% for topping in toppings %}
    <li>
      <p>{{ topping.date_added|date:'M d, Y H:i' }}</p>
      <p>{{ topping.name|linebreaks }}</p>
    </li>
  {% empty %}
    <li>There are no toppings for this pizza yet.</li>
  {% endfor %}
</ul>

{% endblock content %}

pizzeria/pizzas/templates/pizzas/pizzas.html
{% extends "pizzas/base.html" %}


{% block content %}

<p>Pizzas</p>

<ul>
  {% for pizza in pizzas %}
    <li>
      <a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza }}</a>
    </li>
  {% empty %}
    <li>No Pizzas have been added yet.</li>
  {% endfor %}
</ul>

{% endblock content %}